POST http://127.0.0.1:8000/login
Content-Type: application/json

{
            "username": "testConnected",
            "password": "testConnected1234"}
           

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
            "username": "testConnected", 
            "password" : "testConnected1234", 
           "email" : "testConnected@gmail.com"}
###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token b43295e66aaeff6cb7a5c0cc0c755e778e87e1e7

{}

###

POST http://127.0.0.1:8000/post_message
Content-Type: application/json


{
    "room":"ChatRoom(1_4)",
    "sender":1,
    "recipient": 4,
    "message": "Hey"}

###

GET http://127.0.0.1:8000/users
Content-Type: application/json
 
{}

###

POST http://127.0.0.1:8000/create_chatRoom
Content-Type: application/json

{
    "id":"1_4",
    "user_1":4,
    "user_2":1}

###

GET http://127.0.0.1:8000/users/2
Content-Type: application/json

{}

###

GET http://127.0.0.1:8000/get_messages/ChatRoom(2_3)
Content-Type: application/json

{} 
###
GET http://127.0.0.1:8000/get_current_user
Content-Type: application/json
Authorization: Token c1297f7aed64b1933664cad5e44446f5e7d64856


{}
 
###

GET http://127.0.0.1:8000/room/1/2
Content-Type: application/json

{}

###

GET http://127.0.0.1:8000/get_connections
Content-Type: application/json
Authorization: Token 9d38e948433839567d390268026f22521043f3a4

{}
###

