# Generated by Django 5.1.1 on 2025-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/media/profile_pictures/ovaries.jpg', upload_to='profile_pictures'),
        ),
    ]
