# Generated by Django 5.1.1 on 2025-07-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='/profile_pictures/ovaries.jpg'),
        ),
    ]
