# Generated by Django 5.1.1 on 2025-07-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_remove_profile_profile_picture_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='profile', max_length=30),
        ),
    ]
