# Generated by Django 5.1.1 on 2025-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0005_remove_profile_image_url_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(default='https://wxllchqeqxjkpiurgudk.supabase.co/storage/v1/object/public/user-images//OIP.jpg'),
        ),
    ]
