# Generated by Django 5.1.1 on 2026-06-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(default='https://noruhbvggbhumyrrxpja.supabase.co/storage/v1/object/public/user-images/1782038716047_MyImage.jpg'),
        ),
    ]
